use std::fs;
use std::path::Path;
use std::io;

const PANTHON_TOML: &str = r#"[project]
name = "{{name}}"
version = "0.1.0"

[pipeline]
# Define the cell pipeline for this project
# Cells execute in order, each receiving output from the previous
cells = [
  { name = "Planner",  description = "Analyzes requirements and creates implementation plan" },
  { name = "Backend",  description = "Generates and implements code from the plan" },
  { name = "Test",     description = "Runs tests and verifies correctness" },
  { name = "Review",   description = "Reviews implementation quality and security" },
  { name = "Release",  description = "Releases the final artifact" },
]

[pipeline.edges]
"Planner" = "Backend"
"Backend" = "Test"
"Test" = "Review"
"Review" = "Release"
"#;

const MAIN_TEMPLATE: &str = r#"// {{name}} — Generated by Pantheon
// Edit this file to customize your pipeline behavior.

pub fn main() {
    println!("Hello from {{name}}!");
}
"#;

pub fn init_project(name: &str) -> io::Result<()> {
    let dir = Path::new(name);
    if dir.exists() {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            format!("project '{}' already exists", name),
        ));
    }

    fs::create_dir_all(dir.join("cells"))?;
    fs::create_dir_all(dir.join("src"))?;

    let toml = PANTHON_TOML.replace("{{name}}", name);
    fs::write(dir.join("pantheon.toml"), toml)?;

    let main = MAIN_TEMPLATE.replace("{{name}}", name);
    fs::write(dir.join("src").join("mod.rs"), main)?;

    println!("  ✓ Created project '{}'", name);
    println!();
    println!("  Next steps:");
    println!("    cd {}", name);
    println!("    pantheon run");
    println!();

    Ok(())
}
