"""
sync.py — Git sync for evolved skills
Commits, pushes, and creates PRs when new or improved skills are discovered.
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
REPO_DIR = SCRIPT_DIR.parent.parent
REGISTRY_DIR = SCRIPT_DIR / "registry"
STORE_DIR = SCRIPT_DIR / "store"
CONFIG_FILE = SCRIPT_DIR / "sync-config.json"


def log(msg: str):
    ts = datetime.now(timezone.utc).strftime("%H:%M:%S")
    print(f"[{ts}] [SYNC] {msg}")


def load_json(path: Path):
    if path.exists():
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_json(path: Path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def run_git(*args, cwd: Path = None) -> tuple:
    cwd = cwd or REPO_DIR
    try:
        result = subprocess.run(
            ["git"] + list(args),
            capture_output=True, text=True, timeout=60, cwd=cwd,
        )
        return result.returncode == 0, result.stdout.strip(), result.stderr.strip()
    except Exception as e:
        return False, "", str(e)


def get_current_branch() -> str:
    ok, out, _ = run_git("rev-parse", "--abbrev-ref", "HEAD")
    return out if ok else "main"


def has_changes() -> bool:
    ok, out, _ = run_git("status", "--porcelain", "--", str(SCRIPT_DIR))
    return bool(out.strip()) if ok else False


def get_changed_files() -> list:
    ok, out, _ = run_git("status", "--porcelain", "--", str(SCRIPT_DIR))
    if not ok or not out:
        return []
    files = []
    for line in out.split("\n"):
        line = line.strip()
        if not line:
            continue
        status = line[:2].strip()
        filepath = line[3:].strip()
        if filepath:
            files.append({"status": status, "path": filepath})
    return files


def get_config() -> dict:
    defaults = {
        "enabled": False,
        "branch_prefix": "skill-engine-updates",
        "auto_push": False,
        "auto_pr": False,
        "commit_message_template": "chore(skills): evolve {count} skills [{date}]",
        "paths_to_track": [
            "RepublicOS/.skill-engine/registry/",
            "RepublicOS/.skill-engine/store/",
        ],
    }
    cfg = defaults.copy()
    cfg.update(load_json(CONFIG_FILE))
    return cfg


def save_config(cfg: dict):
    save_json(CONFIG_FILE, cfg)
    log(f"Config saved: {CONFIG_FILE}")


def get_change_summary() -> str:
    registry = load_json(REGISTRY_DIR / "skills-registry.json") or []
    evolved = load_json(REGISTRY_DIR / "evolved" / "evolution-log.json") or {}
    quality = load_json(REGISTRY_DIR / "quality.json") or {}
    grades = quality.get("grade_distribution", {}) if isinstance(quality, dict) else {}

    count = len(registry) if isinstance(registry, list) else 0
    evolved_count = evolved.get("total_evolved", 0)
    sections = evolved.get("total_sections_added", 0)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    summary = (
        f"**RepublicOS Skill Engine Update**\n\n"
        f"**Skills:** {count} total, {evolved_count} evolved\n"
        f"**Sections added:** +{sections}\n"
        f"**Grades:** A={grades.get('A', 0)} B={grades.get('B', 0)} "
        f"C={grades.get('C', 0)} D={grades.get('D', 0)}\n"
        f"**Date:** {now}\n\n"
        f"---\n"
        f"*Auto-generated by RepublicOS Skill Engine*"
    )
    return summary


def commit():
    if not has_changes():
        log("No changes to commit")
        return False

    cfg = get_config()
    registry = load_json(REGISTRY_DIR / "skills-registry.json") or []
    evolved = load_json(REGISTRY_DIR / "evolved" / "evolution-log.json") or {}
    count = len(registry) if isinstance(registry, list) else 0
    evolved_count = evolved.get("total_evolved", 0)
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    msg = cfg["commit_message_template"].format(count=evolved_count, total=count, date=date)

    ok, out, err = run_git("add", *cfg["paths_to_track"])
    if not ok:
        log(f"Git add failed: {err}")
        return False

    ok, out, err = run_git("commit", "-m", msg)
    if not ok:
        log(f"Git commit failed: {err}")
        return False

    log(f"Committed: {msg}")
    return True


def push():
    cfg = get_config()
    if not cfg.get("auto_push"):
        log("Auto-push disabled")
        return False

    branch = get_current_branch()
    ok, out, err = run_git("push", "origin", branch)
    if not ok:
        log(f"Push failed: {err}")
        return False

    log(f"Pushed to origin/{branch}")
    return True


def create_pr():
    cfg = get_config()
    if not cfg.get("auto_pr"):
        log("Auto-PR disabled")
        return False

    branch = get_current_branch()
    if branch == "main" or branch == "master":
        log("On main branch, skipping PR")
        return False

    summary = get_change_summary()
    title = f"chore(skills): evolve skills - {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"

    try:
        result = subprocess.run(
            ["gh", "pr", "create", "--title", title, "--body", summary,
             "--base", "main", "--head", branch],
            capture_output=True, text=True, timeout=60, cwd=REPO_DIR,
        )
        if result.returncode == 0:
            log(f"PR created: {result.stdout.strip()}")
            return True
        else:
            log(f"PR failed (gh CLI not available?): {result.stderr}")
            return False
    except FileNotFoundError:
        log("gh CLI not installed. Install GitHub CLI for auto-PR.")
        return False


def sync(auto_commit: bool = True, auto_push: bool = False, auto_pr: bool = False):
    cfg = get_config()
    if not cfg.get("enabled") and not auto_commit:
        log("Sync disabled (enable in sync-config.json or pass --commit)")
        return False

    log(f"Branch: {get_current_branch()}")
    files = get_changed_files()
    if files:
        log(f"Changed files: {len(files)}")
        for f in files[:5]:
            log(f"  [{f['status']}] {f['path']}")

    committed = commit()

    if committed:
        if auto_push or cfg.get("auto_push"):
            push()
        if auto_pr or cfg.get("auto_pr"):
            create_pr()

    return committed


def setup():
    print("=== RepublicOS Sync Setup ===\n")
    cfg = get_config()

    val = input(f"Enable auto-sync? (y/n) [{'y' if cfg['enabled'] else 'n'}]: ").strip().lower()
    if val == "y":
        cfg["enabled"] = True

    val = input(f"Auto-push to remote? (y/n) [{'y' if cfg['auto_push'] else 'n'}]: ").strip().lower()
    if val == "y":
        cfg["auto_push"] = True

    val = input(f"Auto-create PR? (y/n) [{'y' if cfg['auto_pr'] else 'n'}]: ").strip().lower()
    if val == "y":
        cfg["auto_pr"] = True

    val = input(f"Branch prefix [{cfg['branch_prefix']}]: ").strip()
    if val:
        cfg["branch_prefix"] = val

    save_config(cfg)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="RepublicOS Skill Sync")
    parser.add_argument("action", nargs="?", default="status",
                        choices=["status", "sync", "commit", "push", "pr", "setup"],
                        help="Action to perform")
    parser.add_argument("--push", action="store_true", help="Push after commit")
    parser.add_argument("--pr", action="store_true", help="Create PR after commit")

    args = parser.parse_args()

    if args.action == "setup":
        setup()
        return

    if args.action == "status":
        cfg = get_config()
        branch = get_current_branch()
        files = get_changed_files()
        print(f"Branch: {branch}")
        print(f"Enabled: {cfg.get('enabled', False)}")
        print(f"Auto-push: {cfg.get('auto_push', False)}")
        print(f"Auto-PR: {cfg.get('auto_pr', False)}")
        print(f"Changed files: {len(files)}")
        for f in files[:10]:
            print(f"  [{f['status']}] {f['path']}")
        return

    if args.action == "commit":
        commit()
        return

    if args.action == "push":
        push()
        return

    if args.action == "pr":
        create_pr()
        return

    if args.action == "sync":
        sync(auto_commit=True, auto_push=args.push, auto_pr=args.pr)
        return


if __name__ == "__main__":
    main()
